### ISSUE TITLE
EMQX Cluster Setup

### ISSUE THREAD

**Issue by RongTsai4Git** [RongTsai4Git/TechNote#4]
## practice source 
[emqx_cluster practice source](https://github.com/RongTsai4Git/TechNote/tree/master/emqx_cluster)

**Comment by RongTsai4Git** [comment]
## Section Explain: volumes

要集中管理 emqx 相關的設定檔，故統一設定volume讓emqx node參考
```
volumes:
  vol-emqx-data:    // volume symbol, 會在其他段落中使用該名稱做參考
    name: foo-emqx-data   // 實際建立 volume 的名稱
    external: true    // 如果volume已存在，則需要設定該參數為true，這樣docker compose up時才不會因為要去建立 volume 時出現存在相同 volume resource 導致掛載失敗
  vol-emqx-etc:
    name: foo-emqx-etc
    external: true
  vol-emqx-log:
    name: foo-emqx-log
    external: true
```
